# Generated by Django 2.2.7 on 2020-02-03 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import maps.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio')),
            ],
            options={
                'verbose_name': 'Аудио',
                'verbose_name_plural': 'Аудио',
                'db_table': 'audio',
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.SlugField(blank=True, help_text='Если не вводить, то сгенерируется автоматически', max_length=100, null=True, unique=True, verbose_name='Адрес карты')),
                ('title', models.CharField(max_length=255, verbose_name='Название карты')),
                ('description', models.TextField(verbose_name='Краткое описание карты')),
                ('image', models.ImageField(upload_to=maps.models.SaveMapImage('maps/originals'), verbose_name='Изображение карты')),
                ('thumbnail', models.ImageField(upload_to=maps.models.SaveMapImage('maps/thumbnails'), verbose_name='Миниатюра карты')),
                ('width', models.IntegerField(blank=True, verbose_name='Ширина карты')),
                ('height', models.IntegerField(blank=True, verbose_name='Высота карты')),
                ('audio_map', models.TextField(verbose_name='Карта аудио')),
                ('tracks', models.ManyToManyField(to='maps.Audio')),
            ],
            options={
                'verbose_name': 'Карта',
                'verbose_name_plural': 'Карты',
                'db_table': 'maps',
            },
        ),
        migrations.CreateModel(
            name='MapMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Уникальный для данной карты', max_length=255, verbose_name='Заголовок')),
                ('radius', models.PositiveIntegerField(help_text='В пикселях', verbose_name='Радиус метки')),
                ('x_coordinate', models.PositiveIntegerField(help_text='В пикселях', verbose_name='x-координата метки')),
                ('y_coordinate', models.PositiveIntegerField(help_text='В пикселях', verbose_name='y-координата метки')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='maps.Map')),
            ],
            options={
                'verbose_name': 'Метка на карте',
                'verbose_name_plural': 'Метки на карте',
                'db_table': 'map_marks',
                'unique_together': {('title', 'map')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watched_marks', models.ManyToManyField(to='maps.MapMark')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'db_table': 'profiles',
            },
        ),
    ]
