# Generated by Django 2.2.7 on 2020-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='name',
            field=models.CharField(default='Random track', max_length=256, verbose_name='Имя трека'),
        ),
    ]
