# Generated by Django 2.2.7 on 2020-02-03 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_audio_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='name',
            new_name='title',
        ),
    ]
