# Generated by Django 2.2.7 on 2020-02-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20200203_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkDescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('h1', 'Большой заголовок'), ('h3', 'Малый заголовок'), ('img', 'Картинка'), ('paragraph', 'html-Абзац')], max_length=256, verbose_name='Тип')),
                ('content', models.TextField(blank=True, help_text='Используйте теги <a>, <i>, <b> и т.д.', verbose_name='Содержание')),
                ('src', models.FileField(blank=True, upload_to='maps/description', verbose_name='Прикрепить файл')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_description_item', to='maps.MapMark')),
            ],
            options={
                'verbose_name': 'Фрагмент описания метки',
                'verbose_name_plural': 'Описание метки',
                'db_table': 'mark_description_item',
            },
        ),
        migrations.CreateModel(
            name='MapDescriptionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('h1', 'Большой заголовок'), ('h3', 'Малый заголовок'), ('img', 'Картинка'), ('paragraph', 'html-Абзац')], max_length=256, verbose_name='Тип')),
                ('content', models.TextField(blank=True, help_text='Используйте теги <a>, <i>, <b> и т.д.', verbose_name='Содержание')),
                ('src', models.FileField(blank=True, upload_to='maps/description', verbose_name='Прикрепить файл')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_description_item', to='maps.Map')),
            ],
            options={
                'verbose_name': 'Фрагмент описания карты',
                'verbose_name_plural': 'Полное писание карты',
                'db_table': 'map_description_item',
            },
        ),
    ]
