# Generated by Django 2.2.7 on 2020-02-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_mapdescriptionitem_markdescriptionitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markdescriptionitem',
            options={'verbose_name': 'Фрагмент описания метки', 'verbose_name_plural': 'Описания меток'},
        ),
        migrations.AddField(
            model_name='map',
            name='effects',
            field=models.ManyToManyField(blank=True, related_name='sound_effects', to='maps.Audio'),
        ),
        migrations.AddField(
            model_name='map',
            name='effects_map',
            field=models.TextField(blank=True, verbose_name='Карта звуковых эффектов'),
        ),
        migrations.AlterField(
            model_name='map',
            name='tracks',
            field=models.ManyToManyField(related_name='background_tracks', to='maps.Audio'),
        ),
        migrations.AlterField(
            model_name='mapdescriptionitem',
            name='content',
            field=models.TextField(blank=True, help_text='Используйте теги html и т.д.', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='mapdescriptionitem',
            name='map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_description_items', to='maps.Map'),
        ),
        migrations.AlterField(
            model_name='markdescriptionitem',
            name='content',
            field=models.TextField(blank=True, help_text='Используйте теги html.', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='markdescriptionitem',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark_description_items', to='maps.MapMark'),
        ),
    ]
